from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPT = REPO_ROOT / "scripts" / "check_version_sync.py"


def _load_module():
    spec = importlib.util.spec_from_file_location("check_version_sync", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _release_tree(tmp_path: Path) -> Path:
    package = tmp_path / "src" / "sdr_grader"
    package.mkdir(parents=True)
    (package / "__init__.py").write_text(
        '__version__ = "1.2.0"\n',
        encoding="utf-8",
    )
    packs = package / "rules" / "packs"
    for name in ("strict", "pragmatic"):
        pack = packs / name
        pack.mkdir(parents=True)
        (pack / "_meta.yaml").write_text(
            f'pack: {name}\nversion: "2.0"\n',
            encoding="utf-8",
        )
    (tmp_path / "CHANGELOG.md").write_text(
        "## 1.2.0 — 2026-07-29\n\nPack `2.0`; JSON schema `1`.\n",
        encoding="utf-8",
    )
    metadata = tmp_path / ".claude-plugin"
    metadata.mkdir()
    (metadata / "plugin.json").write_text(
        json.dumps({"name": "sdr-grader", "version": "1.2.0"}),
        encoding="utf-8",
    )
    (metadata / "marketplace.json").write_text(
        json.dumps(
            {
                "plugins": [
                    {
                        "name": "sdr-grader",
                        "version": "1.2.0",
                        "source": "./",
                    }
                ]
            }
        ),
        encoding="utf-8",
    )
    examples = tmp_path / "examples"
    examples.mkdir()
    (examples / "grade-cja-clean.html").write_text(
        "Generated by sdr-grader v1.2.0; strict@2.0",
        encoding="utf-8",
    )
    return tmp_path


def test_version_sync_accepts_complete_release_identity(tmp_path, capsys):
    module = _load_module()
    root = _release_tree(tmp_path)

    assert module.main(root, tag="v1.2.0") == 0
    output = capsys.readouterr().out
    assert "package/plugin/marketplace 1.2.0" in output
    assert "packs 2.0" in output


@pytest.mark.parametrize("release_label", ["Unreleased", "2026-13-01"])
def test_version_sync_rejects_non_date_release_heading_when_tagged(
    tmp_path,
    capsys,
    release_label,
):
    module = _load_module()
    root = _release_tree(tmp_path)
    (root / "CHANGELOG.md").write_text(
        f"## 1.2.0 — {release_label}\n\nPack `2.0`; JSON schema `1`.\n",
        encoding="utf-8",
    )

    assert module.main(root, tag="v1.2.0") == 1
    assert "release date" in capsys.readouterr().out.lower()


@pytest.mark.parametrize("tag", ["1.2.0", "v1.2.1", "release-1.2.0"])
def test_version_sync_rejects_malformed_or_mismatched_tag(
    tmp_path,
    capsys,
    tag,
):
    module = _load_module()
    root = _release_tree(tmp_path)

    assert module.main(root, tag=tag) == 1
    assert "tag" in capsys.readouterr().out.lower()


def test_version_sync_rejects_pack_or_report_footer_drift(tmp_path, capsys):
    module = _load_module()
    root = _release_tree(tmp_path / "pack-drift")
    (root / "src/sdr_grader/rules/packs/pragmatic/_meta.yaml").write_text(
        'pack: pragmatic\nversion: "1.0"\n',
        encoding="utf-8",
    )

    assert module.main(root) == 1
    assert "pack" in capsys.readouterr().out.lower()

    root = _release_tree(tmp_path / "report-drift")
    (root / "examples/grade-cja-clean.html").write_text(
        "Generated by sdr-grader v9.9.9; strict@2.0",
        encoding="utf-8",
    )
    assert module.main(root) == 1
    assert "report" in capsys.readouterr().out.lower()
